---
- name: Ensure Julia Downloaded
  get_url:
    url: "{{ url_base }}/linux/{{ bits }}/{{ version }}/julia-{{ version }}.{{ patch }}-{{ binary }}-{{ arch }}.tar.gz"
    dest: /usr/local/tarballs/
    checksum: "sha256:{{ url_base }}/checksums/julia-{{ version }}.{{ patch }}.sha256"
    owner: root
    group: root
    mode: 0644

# https://julialang-s3.julialang.org/bin/linux/x64/1.7/julia-1.7.2-linux-x86_64.tar.gz
# https://julialang-s3.julialang.org/bin/checksums/julia-1.7.2.sha256

# Import signature to gpg

- name: Extract Archive
  unarchive:
    src: /usr/local/tarballs/julia-{{ version }}.{{ patch }}-{{ binary }}-{{ arch }}.tar.gz
    dest: /usr/local/dist/
    remote_src: yes

- name: Create Symbolic Link
  file:
    src: "/usr/local/dist/julia-{{ version }}.{{ patch }}/bin/julia"
    dest: /usr/local/bin/julia
    state: link
    force: yes
