---
- name: Test Roles On Vagrant Box
  hosts: all
  become: yes

  pre_tasks:
    - name: Ensure Apt Cache Updated
      apt:
        update_cache: true
        cache_valid_time: 3600  # 1 hour
    - name: Clean Apt Cache
      apt:
        autoclean: yes

  vars_files:
    - vars.yml

  roles:
    - java
    - networking
    - time
    - utils

  tasks:
    - name: Print Arch
      debug:
        msg: "{{ ansible_machine }}"
    - name: Print Family
      debug:
        msg: "{{ ansible_os_family }}"
    - name: Print Home
      debug:
        msg: "{{ ansible_env.HOME }}"
    - name: Print User
      debug:
        msg: "{{ ansible_user }}"
