
- name: Configure Apt to use Squid
  template:
    src: apt.conf.j2
    dest: /etc/apt/apt.conf.d/apt.conf
    mode: 0644


- name: Ensure Proxy Vars Set
  become: false
  blockinfile:
    path: ~/.bashrc
    marker: "# {mark} EXPORT PROXY VARS"
    block: |
      export http_proxy=http://{{ proxy_host }}:{{ proxy_port }}
      export https_proxy=http://{{ proxy_host }}:{{ proxy_port }}
      export ftp_proxy=http://{{ proxy_host }}:{{ proxy_port }}
